### ISSUE TITLE
 panic: thread 'main' panicked at 'q3 = 0', src/tlsh.rs:211:13

### ISSUE THREAD

**Issue by qy513314** [1crcbl/tlsh-rs#2]
[build_script_build-790ce71eea122247.zip](https://github.com/1crcbl/tlsh-rs/files/8918511/build_script_build-790ce71eea122247.zip)
i put the file into zip for test.
panic:
thread 'main' panicked at 'q3 = 0', src/tlsh.rs:211:13

**Comment by Uinelj** [comment]
Hey, I checked out your fix. It only fixes issue #1 and this one is a different one, right?

**Comment by Uinelj** [comment]
It might be related to https://github.com/trendmicro/tlsh/issues/79.

If I understood correctly the issue, this is not "fixable". However panicking should be replaced by an error.
I can PR this but the repository looks to be inactive. Maybe we should fork?
